- name: setup Mysql
  hosts: server
  become: yes

  vars:
    db_name: "my_database"
    db_user: "my_user"
    db_password: "user123"
    backup_dir: "/backup/mysql"
    backup_schedule: "daily"

  tasks:
  - name: Installing Mysql
    package:
      name: "{{item}}"
      state: present
      update_cache: yes

    loop:
    - mysql-server
    - mysql-client
    - python3-mysqldb
    - libmysqlclient-dev
    become: yes

  - name: start and enable mysql service

    service:
      name: mysql
      state: started
      enabled: yes

  - name: creating mysql user
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: '*.*:ALL'
      host: '%'
      state: present

  - name: create database
    mysql_db:
      name: "{{ db_name }}"
      state: present

  - name: configure backup directory
    file:
      path: "{{ backup_dir }}"
      state: directory
      mode: '0755'

  - name: configure backup cron job
    cron:
      name: "mysql backup"
      minute: "0"
      hour: "2"
      day: "*"
      month: "*"
      weekday: "*"
      job: "mysqldump -u {{ db_user }} -p {{ db_password }} {{ db_name }} > {{ backup_dir }}/{{ db_name }}_{{ backup_schedule }}.sql"
      state: present

  handlers:
  - name: Restart mysql
    service:
      name: mysql
      state: restarted
